name: Rishabh Dwivedi

on: [pull_request, issues]

jobs: Student
  greeting: Thanks for contributing.
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: Thanks for generating issue. I will review it.
        pr-message: Thanks for generating pull request. I will review it.
